---
name: Bug Report
description: Report a bug in ClawdOS
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill in the details below.

  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: A clear description of the bug.
      placeholder: Tell us what you expected vs what actually happened.
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: How can we reproduce the issue?
      value: |
        1.
        2.
        3.
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: ClawdOS version
      placeholder: "v0.2.0"
    validations:
      required: true

  - type: input
    id: openclaw-version
    attributes:
      label: OpenClaw version
      placeholder: "2026.2.x"

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - macOS
        - Linux (Ubuntu/Debian)
        - Linux (Arch)
        - Linux (Other)
        - Windows (WSL)
        - Docker
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant logs
      description: Paste any error messages or console output.
      render: shell

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots.
