---
name: Feature Request
description: Suggest a new feature or improvement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Got an idea? We'd love to hear it.

  - type: textarea
    id: problem
    attributes:
      label: What problem does this solve?
      description: Describe the pain point or use case.
      placeholder: "I often need to..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: How do you envision this working?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any workarounds or alternative approaches?

  - type: dropdown
    id: area
    attributes:
      label: Area
      options:
        - AI / Chat Panel
        - Tasks
        - News / RSS
        - Dashboard
        - Package Tracking
        - Skill Marketplace
        - Settings / Auth
        - Mobile UI
        - DevOps / Deployment
        - Other
    validations:
      required: true

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      options:
        - label: I'm willing to submit a PR for this feature
