schema: content
description: "Контент — дайджесты, новости, RSS-источники, доставки"
version: 4
last_updated: 2026-02-26

# NOTE: Пока таблицы в public.* (локальный этап). Позже переедем в content.*.

tables:
  digest:
    schema: public
    description: "Дайджесты дня (текст)"
    columns:
      id: { type: uuid, primary_key: true, default: gen_random_uuid() }
      workspace_id:
        type: uuid
        nullable: false
        references: public.workspace(id)
        on_delete: CASCADE
      date: { type: date, nullable: false }
      title: { type: text, nullable: false }
      body: { type: text, nullable: false }
      created_at: { type: timestamptz, nullable: false, default: now() }
    constraints:
      - { name: digest_workspace_id_date_key, type: unique, columns: [workspace_id, date] }
    rls:
      enabled: true
      policies:
        - { name: digest_rw, for: ALL, using: "EXISTS (SELECT 1 FROM public.workspace_member m WHERE m.workspace_id = workspace_id AND m.user_id = app_current_user_id())", with_check: "EXISTS (SELECT 1 FROM public.workspace_member m WHERE m.workspace_id = workspace_id AND m.user_id = app_current_user_id())" }

  news_item:
    schema: content
    description: "Новости (лента)"
    columns:
      id: { type: uuid, primary_key: true, default: gen_random_uuid() }
      workspace_id:
        type: uuid
        nullable: false
        references: core.workspace(id)
        on_delete: CASCADE
      topic:
        type: text
        nullable: false
        check: "topic IN ('world','ai','other')"
      title: { type: text, nullable: false }
      url: { type: text, nullable: false }
      summary: { type: text, nullable: false }
      published_at: { type: timestamptz, nullable: true }
      source_id: { type: uuid, nullable: true, references: "content.news_source(id)", on_delete: SET NULL }
      guid: { type: text, nullable: true }
      created_at: { type: timestamptz, nullable: false, default: now() }
    indexes:
      - { name: news_item_ws_topic_created_idx, columns: [workspace_id, topic, created_at], unique: false }
      - { name: news_item_source_idx, columns: [source_id], unique: false }
      - { name: news_item_source_guid_uniq, columns: [source_id, guid], unique: true, where: "guid is not null" }
    rls:
      enabled: true
      policies:
        - { name: news_item_select, for: SELECT, using: "core.is_workspace_member(workspace_id)" }
        - { name: news_item_insert, for: INSERT, with_check: "core.is_workspace_member(workspace_id)" }
        - { name: news_item_update, for: UPDATE, using: "core.is_workspace_member(workspace_id)" }
        - { name: news_item_delete, for: DELETE, using: "core.is_workspace_member(workspace_id)" }

  news_source:
    schema: content
    description: "RSS/Atom/JSON Feed источники"
    columns:
      id: { type: uuid, primary_key: true, default: gen_random_uuid() }
      workspace_id:
        type: uuid
        nullable: false
        references: core.workspace(id)
        on_delete: CASCADE
      url: { type: text, nullable: false }
      title: { type: text, nullable: true }
      feed_type: { type: text, nullable: false, default: "'rss'" }
      status: { type: text, nullable: false, default: "'active'" }
      error_message: { type: text, nullable: true }
      error_count: { type: integer, nullable: false, default: 0 }
      last_fetched_at: { type: timestamptz, nullable: true }
      created_at: { type: timestamptz, nullable: false, default: now() }
      created_by: { type: uuid, nullable: true, references: "core.user(id)", on_delete: SET NULL }
    constraints:
      - { name: news_source_ws_url_uniq, type: unique, columns: [workspace_id, url] }
    indexes:
      - { name: news_source_ws_idx, columns: [workspace_id], unique: false }
      - { name: news_source_ws_status_idx, columns: [workspace_id, status], unique: false }
    rls:
      enabled: true
      policies:
        - { name: news_source_select, for: SELECT, using: "core.is_workspace_member(workspace_id)" }
        - { name: news_source_insert, for: INSERT, with_check: "core.is_workspace_member(workspace_id)" }
        - { name: news_source_update, for: UPDATE, using: "core.is_workspace_member(workspace_id)" }
        - { name: news_source_delete, for: DELETE, using: "core.is_workspace_member(workspace_id)" }

  news_tab:
    schema: content
    description: "Тематические вкладки для группировки источников"
    columns:
      id: { type: uuid, primary_key: true, default: gen_random_uuid() }
      workspace_id:
        type: uuid
        nullable: false
        references: core.workspace(id)
        on_delete: CASCADE
      name: { type: text, nullable: false }
      sort_order: { type: integer, nullable: false, default: 0 }
      created_at: { type: timestamptz, nullable: false, default: now() }
      created_by: { type: uuid, nullable: true, references: "core.user(id)", on_delete: SET NULL }
    indexes:
      - { name: news_tab_ws_idx, columns: [workspace_id], unique: false }
    rls:
      enabled: true
      policies:
        - { name: news_tab_select, for: SELECT, using: "core.is_workspace_member(workspace_id)" }
        - { name: news_tab_insert, for: INSERT, with_check: "core.is_workspace_member(workspace_id)" }
        - { name: news_tab_update, for: UPDATE, using: "core.is_workspace_member(workspace_id)" }
        - { name: news_tab_delete, for: DELETE, using: "core.is_workspace_member(workspace_id)" }

  news_source_tab:
    schema: content
    description: "M:M связь источников и вкладок"
    columns:
      source_id: { type: uuid, nullable: false, references: "content.news_source(id)", on_delete: CASCADE }
      tab_id: { type: uuid, nullable: false, references: "content.news_tab(id)", on_delete: CASCADE }
    constraints:
      - { type: primary_key, columns: [source_id, tab_id] }
    rls:
      enabled: true
      policies:
        - { name: news_source_tab_select, for: SELECT, using: "EXISTS (SELECT 1 FROM content.news_source s WHERE s.id = source_id AND core.is_workspace_member(s.workspace_id))" }
        - { name: news_source_tab_insert, for: INSERT, with_check: "EXISTS (SELECT 1 FROM content.news_source s WHERE s.id = source_id AND core.is_workspace_member(s.workspace_id))" }
        - { name: news_source_tab_delete, for: DELETE, using: "EXISTS (SELECT 1 FROM content.news_source s WHERE s.id = source_id AND core.is_workspace_member(s.workspace_id))" }

  processes:
    schema: content
    description: "Scheduled cron processes for automated tasks"
    columns:
      id: { type: uuid, primary_key: true, default: gen_random_uuid() }
      workspace_id:
        type: uuid
        nullable: false
        references: core.workspace(id)
        on_delete: CASCADE
      title: { type: text, nullable: false }
      description: { type: text, nullable: true }
      schedule:
        type: text
        nullable: false
        description: "Cron format: 0 9 * * *"
      action_type:
        type: text
        nullable: false
        check: "action_type IN ('send_digest','send_reminder','run_backup')"
      action_config: { type: jsonb, nullable: false, default: "'{}'" }
      enabled: { type: boolean, nullable: false, default: true }
      last_run_at: { type: timestamptz, nullable: true }
      next_run_at: { type: timestamptz, nullable: true }
      created_by: { type: uuid, nullable: true, references: "core.user(id)", on_delete: SET NULL }
      created_at: { type: timestamptz, nullable: false, default: now() }
      updated_at: { type: timestamptz, nullable: false, default: now() }
    indexes:
      - { name: processes_workspace_idx, columns: [workspace_id], unique: false }
      - { name: processes_enabled_idx, columns: [enabled], unique: false, where: "enabled = true" }
      - { name: processes_next_run_idx, columns: [workspace_id, next_run_at], unique: false, where: "enabled = true" }
    rls:
      enabled: true
      policies:
        - { name: processes_select, for: SELECT, using: "core.is_workspace_member(workspace_id)" }
        - { name: processes_insert, for: INSERT, with_check: "core.is_workspace_member(workspace_id) AND created_by = core.current_user_id()" }
        - { name: processes_update, for: UPDATE, using: "core.is_workspace_member(workspace_id)", with_check: "core.is_workspace_member(workspace_id)" }
        - { name: processes_delete, for: DELETE, using: "core.is_workspace_member(workspace_id)" }

  delivery:
    schema: content
    description: "Package/shipment tracking (TrackingMore integration)"
    columns:
      id: { type: uuid, primary_key: true, default: gen_random_uuid() }
      workspace_id:
        type: uuid
        nullable: false
        references: core.workspace(id)
        on_delete: CASCADE
      tracking_number: { type: text, nullable: false }
      courier_code: { type: text, nullable: true }
      courier_name: { type: text, nullable: true }
      title: { type: text, nullable: true }
      status:
        type: text
        nullable: false
        default: "'pending'"
        check: "status IN ('pending','transit','pickup','delivered','expired','undelivered')"
      substatus: { type: text, nullable: true }
      origin: { type: text, nullable: true }
      destination: { type: text, nullable: true }
      eta: { type: timestamptz, nullable: true }
      last_event: { type: text, nullable: true }
      last_event_at: { type: timestamptz, nullable: true }
      trackingmore_id: { type: text, nullable: true }
      events: { type: jsonb, nullable: false, default: "'[]'" }
      created_by: { type: uuid, nullable: true, references: "core.user(id)", on_delete: SET NULL }
      created_at: { type: timestamptz, nullable: false, default: now() }
      updated_at: { type: timestamptz, nullable: false, default: now() }
    constraints:
      - { name: delivery_ws_tracking_uniq, type: unique, columns: [workspace_id, tracking_number] }
    indexes:
      - { name: delivery_workspace_idx, columns: [workspace_id], unique: false }
      - { name: delivery_workspace_status_idx, columns: [workspace_id, status], unique: false }
      - { name: delivery_tracking_number_idx, columns: [tracking_number], unique: false }
    rls:
      enabled: true
      policies:
        - { name: delivery_select, for: SELECT, using: "core.is_workspace_member(workspace_id)" }
        - { name: delivery_insert, for: INSERT, with_check: "core.is_workspace_member(workspace_id) AND created_by = core.current_user_id()" }
        - { name: delivery_update, for: UPDATE, using: "core.is_workspace_member(workspace_id)", with_check: "core.is_workspace_member(workspace_id)" }
        - { name: delivery_delete, for: DELETE, using: "core.is_workspace_member(workspace_id)" }
